terminal.shell = "bash"
[general]
live_config_reload = true
import = [
#"~/.config/alacritty/themes/dayfox_light.toml",
"~/.config/alacritty/themes/ashes/ashes_dark.toml"
]

[font]
size = 11.0
normal = {family="IosevkaTermNerdFontPropo", style="Regular"}
bold = {family="IosevkaTermNerdFontPropo", style="Bold"}
italic = {family="IosevkaTermNerdFontPropo", style="Italic"}

[window]
padding = { x = 0, y = 0 }
dynamic_padding = true
opacity = 1

