shell = "fish"
live_config_reload = true
import = [
#"~/.config/alacritty/themes/ashes/ashes_light.toml",
"~/.config/alacritty/themes/ashes/ashes_dark.toml"
]

[font]
size = 11.0
normal = {family="0xProto Nerd Font Propo", style="Regular"}
bold = {family="0xProto", style="Bold"}
italic = {family="0xProto", style="Italic"}

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 1

